// scripts/initCurrencies.js
const Currency = require('../Models/Currency');

// Stripe-supported currencies (full list from your Excel file)
const stripeSupportedCurrencies = [
  { code: 'USD', name: 'US Dollar', symbol: '$', countries: [
    'AMERICAN SAMOA', 'BONAIRE', 'ECUADOR', 'EL SALVADOR', 'GUAM', 
    'MARSHALL ISLANDS', 'MICRONESIA, FEDERATED STATES OF', 
    'NORTHERN MARIANA ISLANDS', 'PALAU', 'PANAMA', 'PUERTO RICO', 
    'TIMOR-LESTE', 'TURKS AND CAICOS ISLANDS', 'UNITED STATES', 
    'VIRGIN ISLANDS (US)'
  ], isDefault: false },
  
  { code: 'EUR', name: 'Euro', symbol: '€', countries: [
    'ALAND ISLANDS', 'ANDORRA', 'AUSTRIA', 'BELGIUM', 'CYPRUS', 'ESTONIA', 
    'FINLAND', 'FRANCE', 'GERMANY', 'GREECE', 'IRELAND', 'ITALY', 'LUXEMBOURG', 
    'MALTA', 'MONACO', 'MONTENEGRO', 'NETHERLANDS', 'PORTUGAL', 'SAN MARINO', 
    'SLOVAKIA', 'SLOVENIA', 'SPAIN', 'Vatican City State (HOLY SEE)'
  ], isDefault: true },
  
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', countries: ['UNITED ARAB EMIRATES'] },
  { code: 'AFN', name: 'Afghani', symbol: '؋', countries: ['AFGHANISTAN'] },
  { code: 'ALL', name: 'Lek', symbol: 'L', countries: ['ALBANIA'] },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', countries: ['ARMENIA'] },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', countries: ['CURACAO', 'SINT MAARTEN (DUTCH PART)'] },
  { code: 'AOA', name: 'Kwanza', symbol: 'Kz', countries: ['ANGOLA'] },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', countries: ['ARGENTINA'] },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', countries: ['AUSTRALIA'] },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', countries: ['ARUBA'] },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', countries: ['AZERBAIJAN'] },
  { code: 'BAM', name: 'Convertible Mark', symbol: 'KM', countries: ['BOSNIA AND HERZEGOVINA'] },
  { code: 'BBD', name: 'Barbados Dollar', symbol: 'Bds$', countries: ['BARBADOS'] },
  { code: 'BDT', name: 'Taka', symbol: '৳', countries: ['BANGLADESH'] },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', countries: ['BULGARIA'] },
  { code: 'BIF', name: 'Burundi Franc', symbol: 'FBu', countries: ['BURUNDI'] },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: 'BD$', countries: ['BERMUDA'] },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', countries: ['BRUNEI DARUSSALAM'] },
  { code: 'BOB', name: 'Boliviano', symbol: 'Bs.', countries: ['BOLIVIA'] },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', countries: ['BRAZIL'] },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: 'B$', countries: ['BAHAMAS'] },
  { code: 'BWP', name: 'Pula', symbol: 'P', countries: ['BOTSWANA'] },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', countries: ['BELARUS'] },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', countries: ['BELIZE'] },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$', countries: ['CANADA'] },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', countries: ['CONGO'] },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', countries: ['SWITZERLAND'] },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CLP$', countries: ['CHILE'] },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', countries: ['CHINA'] },
  { code: 'COP', name: 'Colombian Peso', symbol: 'COL$', countries: ['COLOMBIA'] },
  { code: 'CRC', name: 'Costa Rican Colon', symbol: '₡', countries: ['COSTA RICA'] },
  { code: 'CVE', name: 'Cape Verde Escudo', symbol: 'Esc', countries: ['CAPE VERDE'] },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', countries: ['CZECH REPUBLIC'] },
  { code: 'DJF', name: 'Djibouti Franc', symbol: 'Fdj', countries: ['DJIBOUTI'] },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', countries: ['DENMARK'] },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', countries: ['DOMINICAN REPUBLIC'] },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', countries: ['ALGERIA'] },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', countries: ['EGYPT'] },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', countries: ['ETHIOPIA'] },
  { code: 'FJD', name: 'Fiji Dollar', symbol: 'FJ$', countries: ['FIJI'] },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: 'FK£', countries: ['FALKLAND ISLANDS'] },
  { code: 'GBP', name: 'British Pound', symbol: '£', countries: ['UNITED KINGDOM'] },
  { code: 'GEL', name: 'Lari', symbol: '₾', countries: ['GEORGIA'] },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', countries: ['GIBRALTAR'] },
  { code: 'GMD', name: 'Dalasi', symbol: 'D', countries: ['GAMBIA'] },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', countries: ['GUINEA'] },
  { code: 'GTQ', name: 'Quetzal', symbol: 'Q', countries: ['GUATEMALA'] },
  { code: 'GYD', name: 'Guyana Dollar', symbol: 'GY$', countries: ['GUYANA'] },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', countries: ['HONG KONG'] },
  { code: 'HNL', name: 'Lempira', symbol: 'L', countries: ['HONDURAS'] },
  { code: 'HTG', name: 'Gourde', symbol: 'G', countries: ['HAITI'] },
  { code: 'HUF', name: 'Forint', symbol: 'Ft', countries: ['HUNGARY'] },
  { code: 'IDR', name: 'Rupiah', symbol: 'Rp', countries: ['INDONESIA'] },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', countries: ['ISRAEL'] },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', countries: ['INDIA'] },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', countries: ['ICELAND'] },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', countries: ['JAMAICA'] },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', countries: ['JAPAN'] },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', countries: ['KENYA'] },
  { code: 'KGS', name: 'Som', symbol: 'с', countries: ['KYRGYZSTAN'] },
  { code: 'KHR', name: 'Riel', symbol: '៛', countries: ['CAMBODIA'] },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', countries: ['COMOROS'] },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', countries: ['SOUTH KOREA'] },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'CI$', countries: ['CAYMAN ISLANDS'] },
  { code: 'KZT', name: 'Tenge', symbol: '₸', countries: ['KAZAKHSTAN'] },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', countries: ['LAOS'] },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', countries: ['LEBANON'] },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', countries: ['SRI LANKA'] },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', countries: ['LIBERIA'] },
  { code: 'LSL', name: 'Loti', symbol: 'L', countries: ['LESOTHO'] },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', countries: ['MOROCCO'] },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', countries: ['MOLDOVA'] },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', countries: ['MADAGASCAR'] },
  { code: 'MKD', name: 'Denar', symbol: 'ден', countries: ['NORTH MACEDONIA'] },
  { code: 'MMK', name: 'Kyat', symbol: 'K', countries: ['MYANMAR'] },
  { code: 'MNT', name: 'Tugrik', symbol: '₮', countries: ['MONGOLIA'] },
  { code: 'MOP', name: 'Pataca', symbol: 'MOP$', countries: ['MACAU'] },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', countries: ['MAURITIUS'] },
  { code: 'MVR', name: 'Rufiyaa', symbol: 'Rf', countries: ['MALDIVES'] },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', countries: ['MALAWI'] },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', countries: ['MEXICO'] },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', countries: ['MALAYSIA'] },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', countries: ['MOZAMBIQUE'] },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', countries: ['NAMIBIA'] },
  { code: 'NGN', name: 'Naira', symbol: '₦', countries: ['NIGERIA'] },
  { code: 'NIO', name: 'Cordoba Oro', symbol: 'C$', countries: ['NICARAGUA'] },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', countries: ['NORWAY'] },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', countries: ['NEPAL'] },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', countries: ['NEW ZEALAND'] },
  { code: 'PAB', name: 'Balboa', symbol: 'B/.', countries: ['PANAMA'] },
  { code: 'PEN', name: 'Sol', symbol: 'S/', countries: ['PERU'] },
  { code: 'PGK', name: 'Kina', symbol: 'K', countries: ['PAPUA NEW GUINEA'] },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', countries: ['PHILIPPINES'] },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', countries: ['PAKISTAN'] },
  { code: 'PLN', name: 'Zloty', symbol: 'zł', countries: ['POLAND'] },
  { code: 'PYG', name: 'Guarani', symbol: '₲', countries: ['PARAGUAY'] },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', countries: ['QATAR'] },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', countries: ['ROMANIA'] },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', countries: ['SERBIA'] },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', countries: ['RUSSIA'] },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', countries: ['RWANDA'] },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', countries: ['SAUDI ARABIA'] },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', countries: ['SOLOMON ISLANDS'] },
  { code: 'SCR', name: 'Seychelles Rupee', symbol: '₨', countries: ['SEYCHELLES'] },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', countries: ['SWEDEN'] },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', countries: ['SINGAPORE'] },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', countries: ['SAINT HELENA'] },
  { code: 'SLL', name: 'Leone', symbol: 'Le', countries: ['SIERRA LEONE'] },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', countries: ['SOMALIA'] },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', countries: ['SURINAME'] },
  { code: 'STD', name: 'Dobra', symbol: 'Db', countries: ['SAO TOME AND PRINCIPE'] },
  { code: 'SZL', name: 'Lilangeni', symbol: 'L', countries: ['ESWATINI'] },
  { code: 'THB', name: 'Baht', symbol: '฿', countries: ['THAILAND'] },
  { code: 'TJS', name: 'Somoni', symbol: 'ЅМ', countries: ['TAJIKISTAN'] },
  { code: 'TOP', name: 'Paʻanga', symbol: 'T$', countries: ['TONGA'] },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', countries: ['TURKEY'] },
  { code: 'TTD', name: 'Trinidad Dollar', symbol: 'TT$', countries: ['TRINIDAD AND TOBAGO'] },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', countries: ['TAIWAN'] },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', countries: ['TANZANIA'] },
  { code: 'UAH', name: 'Hryvnia', symbol: '₴', countries: ['UKRAINE'] },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', countries: ['UGANDA'] },
  { code: 'UYU', name: 'Peso Uruguayo', symbol: '$U', countries: ['URUGUAY'] },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'soʻm', countries: ['UZBEKISTAN'] },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', countries: ['VIETNAM'] },
  { code: 'VUV', name: 'Vatu', symbol: 'VT', countries: ['VANUATU'] },
  { code: 'WST', name: 'Tala', symbol: 'WS$', countries: ['SAMOA'] },
  { code: 'XAF', name: 'CFA Franc BEAC', symbol: 'FCFA', countries: ['CAMEROON'] },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', countries: ['ANGUILLA'] },
  { code: 'XOF', name: 'CFA Franc BCEAO', symbol: 'CFA', countries: ['BENIN'] },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', countries: ['FRENCH POLYNESIA'] },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', countries: ['YEMEN'] },
  { code: 'ZAR', name: 'Rand', symbol: 'R', countries: ['SOUTH AFRICA'] },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', countries: ['ZAMBIA'] }
];

async function initCurrencies() {
  try {
    await Currency.deleteMany({});
    
    for (const currency of stripeSupportedCurrencies) {
      await Currency.create({
        ...currency,
        stripeSupported: true
      });
    }

    console.log(`✅ Successfully initialized ${stripeSupportedCurrencies.length} Stripe-supported currencies`);
  } catch (error) {
    console.error('❌ Error initializing currencies:', error);
    throw error;
  }
}

module.exports = initCurrencies;